language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
install:
  - npm install
script:
  - npm test
after_success:
  - npm run semantic-release
  - npm run coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
